import { Mongo } from "meteor/mongo";

export const Employee = new Mongo.Collection("employees");

export const educationCategory = [
  { code: 10, label: "SD" },
  { code: 20, label: "SMP" },
  { code: 30, label: "SMU" },
  { code: 31, label: "SMA" },
  { code: 32, label: "SMK" },
  { code: 33, label: "STM" },
  { code: 34, label: "SPG" },
  { code: 35, label: "SMPS" },
  { code: 36, label: "SMEA" },
  { code: 37, label: "D1" },
  { code: 38, label: "D2" },
  { code: 39, label: "D3" },
  { code: 40, label: "S1" },
  { code: 50, label: "S2" },
  { code: 60, label: "S3" },
];

export const EmployeeStatus = [
  { label: "Pegawai Tetap Yayasan (PTY)", code: "pty" },
  { label: "Pegawai Tetap Perwakilan (PTP)", code: "ptp" },
  { label: "Pegawai Tidak Tetap (PTT)", code: "ptt" },
  { label: "Resign", code: "resign" },
  { label: "Pensiun", code: "pensiun" },
  { label: "Salah Unit Kerja", code: "suk" },
];

export const EmployeeGolongan = [
  { label: "I/a	Juru Muda", code: "I/a" },
  { label: "I/b	Juru Muda Tingkat I", code: "I/b" },
  { label: "I/c	Juru", code: "I/c" },
  { label: "I/d	Juru Tingkat I", code: "I/d" },
  { label: "II/a	Pengatur Muda", code: "II/a" },
  { label: "II/b	Pengatur Muda Tingkat I", code: "II/b" },
  { label: "II/c	Pengatur", code: "II/c" },
  { label: "II/d	Pengatur Tingkat I", code: "II/d" },
  { label: "III/a	Penata Muda", code: "III/a" },
  { label: "III/b	Penata Muda Tingkat I", code: "III/b" },
  { label: "III/c	Penata", code: "III/c" },
  { label: "III/d	Penata Tingkat I", code: "III/d" },
  { label: "IV/a	Pembina", code: "IV/a" },
  { label: "IV/b	Pembina Tingkat I", code: "IV/b" },
];

export const EmployeeTemplate = [
  {
    name: "fullName",
    type: "text",
    mode: 1,
    label: "Nama Lengkap",
  },
  {
    name: "gelar",
    type: "text",
    mode: 1,
    label: "Gelar",
  },
  {
    name: "identificationNumber",
    type: "text",
    mode: 1,
    label: "NIK",
  },
  {
    name: "placeOfBirth",
    type: "text",
    mode: 1,
    label: "Kota Lahir",
  },
  {
    name: "dateOfBirth",
    type: "date",
    mode: 1,
    label: "Tanggal Lahir",
  },
  {
    name: "religi",
    type: "select",
    mode: 2,
    label: "Agama",
  },
  {
    name: "gender",
    type: "select",
    mode: 2,
    label: "Jenis Kelamin",
  },
  {
    name: "golonganDarah",
    type: "select",
    mode: 2,
    label: "Golongan Darah",
  },
  {
    name: "motherName",
    type: "text",
    mode: 1,
    label: "Nama Ibu Kandung",
  },
  {
    name: "npwp",
    type: "text",
    mode: 1,
    label: "NPWP",
  },
  {
    name: "address",
    type: "text",
    mode: 1,
    label: "Alamat Domisili",
  },
  {
    name: "marrital",
    type: "select",
    mode: 2,
    label: "Status Pernikahan",
  },
  {
    name: "numberOfChildren",
    type: "number",
    mode: 1,
    label: "Jumlah Anak",
  },
  {
    name: "postal",
    type: "number",
    mode: 1,
    label: "Kode Pos",
  },
  {
    name: "schoolUnit",
    type: "select",
    mode: 2,
    label: "Unit Kerja",
  },
  {
    name: "npsn",
    type: "text",
    mode: 1,
    label: "NPSN",
  },
  {
    name: "jenjang",
    type: "text",
    mode: 1,
    label: "Jenjang",
  },
  {
    name: "perwakilan",
    type: "text",
    mode: 1,
    label: "Perwakilan",
  },
  {
    name: "cityUnit",
    type: "text",
    mode: 1,
    label: "Kota/Kabupaten",
  },
  {
    name: "highEducation",
    type: "select",
    mode: 2,
    label: "Pendidikan Terakhir",
  },
  {
    name: "educationInstitution",
    type: "text",
    mode: 1,
    label: "Nama Intansi Pendidikan Terakhir",
  },
  {
    name: "major",
    type: "text",
    mode: 1,
    label: "Jurusan",
  },
  {
    name: "educationGraduate",
    type: "number",
    mode: 1,
    label: "Tahun Lulus",
  },
  {
    name: "startDateWorking",
    type: "date",
    mode: 1,
    label: "Tanggal Mulai Bekerja",
  },
  {
    name: "startDateWorkSk",
    type: "date",
    mode: 1,
    label: "TMT Kerja Sesuai SK",
  },
  {
    name: "startDateAngkatanSk",
    type: "date",
    mode: 1,
    label: "Tanggal Angkatan SK",
  },
  {
    name: "endDateWorkSk",
    type: "date",
    mode: 1,
    label: "Selesai Masa Berlaku SK",
  },
  {
    name: "employmentStatus",
    type: "select",
    mode: 2,
    label: "Status Pegawai",
  },
  {
    name: "tuk",
    type: "text",
    mode: 1,
    label: "TUK",
  },
  {
    name: "selectedPosition",
    type: "select",
    mode: 2,
    label: "Jabatan (Sesuai SK)",
  },
  {
    name: "notePosition",
    type: "text",
    mode: 1,
    label: "Keterangan Jabatan / Tugas Tambahan",
  },
  {
    name: "selectedGol",
    type: "select",
    mode: 2,
    label: "Golongan/RU",
  },
  {
    name: "nuptk",
    type: "text",
    mode: 1,
    label: "NUPTK",
  },
  {
    name: "sertifikasiNumber",
    type: "text",
    mode: 1,
    label: "No. Sertifikasi",
  },
  {
    name: "sertifikasiNumber2",
    type: "text",
    mode: 1,
    label: "No. Sertf. Guru Penggerak",
  },
  {
    name: "nuks",
    type: "text",
    mode: 1,
    label: "NUKS / NRKS",
  },
  {
    name: "bpjsTK",
    type: "checkbox",
    mode: 1,
    label: "Kepesertaan BPJS Ketenagakerjaan",
  },
  {
    name: "dateBpjsTK",
    type: "date",
    mode: 1,
    label: "Tanggal Kepesertaan BPJS Ketenagakerjaan (OPSIONAL)",
  },
  {
    name: "amountBpjsTK",
    type: "text",
    mode: 1,
    label: "Upah yang didaftarkan",
  },
  {
    name: "npp",
    type: "text",
    mode: 1,
    label: "NPP",
  },
  {
    name: "companyName",
    type: "text",
    mode: 1,
    label: "Nama Perusahaan",
  },
  {
    name: "kepesertaanBpjsKes",
    type: "select",
    mode: 2,
    label: "Kepesertaan BPJS Kesehatan",
  },
  {
    name: "dateBpjsKS",
    type: "date",
    mode: 1,
    label: "Tanggal Kepesertaan BPJS Kesehatan (OPSIONAL)",
  },
  {
    name: "amountBpjsKS",
    type: "text",
    mode: 1,
    label: "UMK yang didaftarkan",
  },
  {
    name: "noteBpjsKS",
    type: "text",
    mode: 1,
    label: "Keterangan",
  },
  {
    name: "phoneNumber",
    type: "text",
    mode: 1,
    label: "Nomor Telepon",
  },
  {
    name: "email",
    type: "email",
    mode: 1,
    label: "E-mail",
  },
  {
    name: "emergencyContactName",
    type: "text",
    mode: 1,
    label: "Nama Kontak Darurat",
  },
  {
    name: "emergencyContactPhone",
    type: "text",
    mode: 1,
    label: "Nomor Kontak Darurat",
  },
];
